
--UPDATE CLIENTES SET ATIVO = '0' FROM CLIENTES

--SELECT * FROM CLIENTES

--UPDATE PRESTADORES SET ATIVO = '0' FROM PRESTADORES

--SELECT * FROM PRESTADORES

-- ADICIONAR COLUNAS
--ALTER TABLE dbo.Prestadores ADD ATIVO INT NULL


--DELETAR COLUNAS
--ALTER TABLE Prestadores DROP COLUMN LOGO 